
development:
  adapter: mysql
  encoding: utf8
  database: maps_development
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: maps_test
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: maps_production
  username: 
  password: 
